#!/bin/sh
# install python packages via pipx

pipx install \
	animdl \
	cppman \
	git+https://github.com/dogeystamp/testr

pipx install python-lsp-server
pipx inject python-lsp-server \
	python-lsp-black \
	pylsp-mypy
