[window]
padding = { x = 8, y = 8 }
opacity = 0.1
startup_mode = "Maximized"
decorations = "None"

[font]
normal = { family = "JetBrainsMono NF" }
size = 10
[colors]
[colors.primary]
background = "#000000"

[colors.normal]
black =   "#000000"
red =     "#afaaaa"
green =   "#505559"
yellow =  "#a7a7a7"
blue =    "#56698a"
magenta = "#d5d5d5"
cyan =    "#99AABB"
white =   "#e5e9f0"


[colors.bright]
black =   "#4c566a"
red =     "#bf616a"
green =   "#a3be8c"
yellow =  "#ebcb8b"
blue =    "#81a1c1"
magenta = "#b48ead"
cyan =    "#8fbcbb"
white =   "#eceff4"

[keyboard]
bindings = [
	{ key = "Enter", mods = "Control|Shift", action = "CreateNewWindow" },
	{ key = "l", mods = "Control|Shift", action = "ClearHistory" },
]

[bell]
animation = "EaseOutQuint"
duration = 150
color = "#000000"

# uRls
[[hints.enabled]]
action          = "Copy"
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
binding         = { key = "R", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|go‐pher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

# git coMmits
[[hints.enabled]]
action          = "Copy"
post_processing = true
persist         = false
mouse.enabled   = true
hyperlinks=true
binding         = { key = "M", mods = "Control" }
regex           = "[0-9a-f]{7,40}"
