#!/usr/bin/env python
"""
Compile greek letters into xcompose file.

    ./greek.py > greek
"""

greeks = "ΑαΒβΔδΕεΦφΓγΗηΙιΘθΚκΛλΜμΝνΟοΠπΧχΡρΣσΤτΥυΩωΞξΨψΖζ"
romans = "AaBbDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuWwXxYyZz"
prefix = "<Multi_key> <g>"

print("# This file is autogenerated by greek.py.\n")
for greek, roman in zip(greeks, romans):
    print(f"{prefix} <{roman}> : \"{greek}\"")
