status_path "~/.local/share/pimsync/status/"

storage calendars_remote {
  type caldav
  url http://oriens:5232
  username dogeystamp
  password {
    shell cat ~/.config/pimsync/password
  }
}

storage calendars_local {
  type vdir/icalendar
  path ~/.local/share/calendars/
  fileext ics
}

pair calendars {
  storage_a calendars_local
  storage_b calendars_remote
  collections all
}
