theme = "base16_system"

[editor]
line-number = "relative"
scrolloff = 0
completion-timeout = 5
end-of-line-diagnostics = "hint"
jump-label-alphabet = "asdfghjkl"
popup-border = "all"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.statusline]
left = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = ["version-control", "spacer", "diagnostics", "spacer", "spinner"]

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.gutters.line-numbers]
min-width = 2

[keys.normal]

# note these are switched from the default vim binds
"^" = "goto_line_start"
0 = "goto_first_nonwhitespace"

"$" = "goto_line_end"
G = "goto_file_end"
S = "surround_add"
"C-r" = "redo"
"C-j" = "rotate_view"
"C-k" = "rotate_view_reverse"
C = ["collapse_selection", "extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
"C-c" = ["copy_selection_on_next_line"] # enter multi-cursor mode

[keys.select]
G = "goto_file_end"
"^" = "goto_line_start"
0 = "goto_first_nonwhitespace"
"$" = "goto_line_end"
S = "surround_add"

[keys.normal.Z]
Z = [":write-quit"]
Q = [":quit!"]
# this is my bind
F = [":quit-all"]

[keys.insert]
esc = ["move_char_left", "normal_mode"]
"C-s" = "signature_help"
"C-f" = "completion"
